# Generated by Django 2.1.3 on 2018-12-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181205_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='song_name',
        ),
    ]
